### ISSUE TITLE
This session would have handled too many guilds

### ISSUE THREAD

**Issue by PhunStyle** [DevYukine/Kurasuta#106]
So i'm not sure if i'm doing something wrong but even just the base code in the example doesn't work for me.

It calculates the required amount of shards correctly but immediately throws an error:
![Selection_024](https://user-images.githubusercontent.com/6770468/54921518-3fc84b80-4f06-11e9-89fc-df7741a3292b.png)

**Comment by Dev-Yukine** [comment]
do you manually set a shardCount which is 1 while you need more then 1 shard?

**Comment by PhunStyle** [comment]
I'm just using the basic code in your readme file. I just wanted to see if i could move on from discordie since it is no longer being maintained, bot's on about 19k guilds.

What's weird is that sharding without clusters works on the base discord.js library and it connects without any error. What's even weirder is that if I change guildsPerShard to a low number like 500, it spawns like 36 shards and works fine but for some reason with the default options it throws this error.

**Comment by Dev-Yukine** [comment]
Yea this issue seems definitly related to this library, whats weird is that my bot on 95k Guilds runs fine, could you show me your d.js client options and the kurasuta options you pass?

**Comment by PhunStyle** [comment]
Sure, this is all i got cause it's just based on your sample. I'm starting from scratch.

index.js
```
require('./Util/loadconfig');
const logger = require('./Util/logger');
const nconf = require('nconf');

const { ShardingManager } = require('kurasuta');
const { join } = require('path');

const { isMaster } = require('cluster');

const sharder = new ShardingManager(join(__dirname, 'main'), {
	// your options here
	token: nconf.get('TOKEN'),
	ipcSocket: 9999,
	guildsPerShard: 1000,
	development: true
});

sharder.on('debug', message => {
  logger.info(message);
});

sharder.spawn();
```

main.js

```const nconf = require('nconf');
const logger = require('./Util/logger');

const { BaseCluster } = require('kurasuta');

module.exports = class extends BaseCluster {
	launch() {
		this.client
		.on('debug', (...toLog) => {
			logger.info(...toLog);
		})
		.on('ready', () => {
			logger.success('Logged in!');
		})
		this.client.login(nconf.get('TOKEN'));
	}
};
```

**Comment by PhunStyle** [comment]
Any update on this? Probably hard to test.

**Comment by Kashalls** [comment]
Just a quick question @DevYukine , how many cores does your server running your 95k have? I assume @PhunStyle still has a 4 core machine right?

**Comment by PhunStyle** [comment]
> Just a quick question @DevYukine , how many cores does your server running your 95k have? I assume @PhunStyle still has a 4 core machine right?

That's correct

**Comment by PhunStyle** [comment]
> Just a quick question @DevYukine , how many cores does your server running your 95k have? I assume @PhunStyle still has a 4 core machine right?

So your reply got me thinking and changing clusterCount to 2 instead of the automatically selected 4 (by cpus().length) it started working...

**Comment by PhunStyle** [comment]
> > Just a quick question @DevYukine , how many cores does your server running your 95k have? I assume @PhunStyle still has a 4 core machine right?
> 
> So your reply got me thinking and changing clusterCount to 2 instead of the automatically selected 4 (by cpus().length) it started working...

So i started logging all the incoming command messages to the bot and i saw duplicates after making the change to the clusterCount...

So now it makes sense, kind of. The maximum amount of guilds on a shard is 2500 iirc. It won't connect with 3 cpus cause there'd be 3 duplicates (3000) but if i change the guildsPerShard to 500, it will connect with the clusterCount set to auto or 4 just fine, but i will get 4 duplicate messages.

![image](https://user-images.githubusercontent.com/6770468/58178886-55a88180-7ca7-11e9-9ecb-2346437bf520.png)

So for some reason the script isn't moving the shards on the other cpus but rather every worker is trying to start from shard 0??? Is that what i'm understanding here?

**Comment by DevYukine** [comment]
Hey, this seems stale, do you still encounter this on the latest version?

**Comment by PhunStyle** [comment]
Last time i used it i didn't encounter this but i did have a slightly newer node version when i did - Do you have a node version you recommend using? I'll try again soon and comment if i find it still does the same thing.

**Comment by DevYukine** [comment]
i can recommend LTS (currently 12.x), thats what i used it with in production.

**Comment by PhunStyle** [comment]
Somewhere along the lines some math has to be going wrong - that or i don't know where the other 10k guilds come from.

If i set the sharding to happen automagically by adding a token (1000 guilds per shard on a 22k bot) then the math would work out to 22 shards -> I get an error message saying that sharding is required (session would've handled too many guilds). 

If i change that and don't set the token but set 30 shards (1000 guilds per shard again, 22k bot) then it should be able to handle 30,000 guilds - but even then the bot errors with the same error message.

It is only at 33 shards that it starts working - is that because of the fact that it counts DM interactions as extra guilds?

Cheers!

**Comment by PhunStyle** [comment]
![image](https://user-images.githubusercontent.com/6770468/76713258-91717380-671f-11ea-85da-6241d5095cbd.png)

Edit: Well it starts working, but it doesn't keep working.

**Comment by PhunStyle** [comment]
I'm happy to report that during one of your updates the error went away, thanks! :)c

**Comment by DevYukine** [comment]
Good to hear :)

**Comment by TheNoob27** [comment]
I'm still having this issue on the latest version of kurasuta, clusters set to 4 and shards 16
