### ISSUE TITLE
TypeScript usage for shard util

### ISSUE THREAD

**Issue by UnsecPhu** [DevYukine/Kurasuta#146]
Since discord.js ShardClientUtil and kurasuta ShardClientUtil are different
how do we use the kurasuta only functions like masterEval in typescript?

It isn't showing up with client#shard

**Comment by DevYukine** [comment]
i fixed this in https://github.com/DevYukine/Kurasuta/commit/9c8be0fce57680366f58ce16ffce14f513c81ddd by adding all missing Add missing methods, properties & overloads to ShardClientUtil 👍
