### ISSUE TITLE
Not spawning more shards then 3

### ISSUE THREAD

**Issue by RoelofNoort** [DevYukine/Kurasuta#261]
So, I tried to implement it in my current bot, but for some reason it doesn't work.. I defined I want 8 shards, on 4 clusters, but it only spawns 3?

**Comment by DevYukine** [comment]
wdym by it only spawns 3? i tried to reproduce locally and it worked for me 👀

**Comment by DevYukine** [comment]
Hey, this seems stale, do you still encounter this on the latest version?

**Comment by DevYukine** [comment]
This seems stale so i will close it for now, feel free to re-open if you encounter this on latest Kurasuta version
