### ISSUE TITLE
How to determine shard ID?

### ISSUE THREAD

**Issue by pizzafox** [DevYukine/Kurasuta#344]
How can a shard determine its shard ID? `ShardClientUtil.id` is always `0`, so I can't use that. Does Kurasuta expose an environment variable to clustered processes?

**Comment by DevYukine** [comment]
Hey,

what do you mean exactly by "shard id", a cluster can have multiple shards and to check which one you can check `Client#shards` which is a collection of Shards mapped by there id. Also ShardClientUtil.id is used for the **Cluster** id not Shard Id

**Comment by pizzafox** [comment]
The client does not have a `shards` property or method according to Discord.js master docs. Are you sure that's correct?

**Comment by DevYukine** [comment]
Oh im sorry i forgot this is located on the WebsocketManager, it should be `Client#ws#shards`

**Comment by DevYukine** [comment]
This seems answered :)
