### ISSUE TITLE
Getting cluster by shard ID

### ISSUE THREAD

**Issue by Puyodead1** [DevYukine/Kurasuta#375]
Hi, I want to add stats into a command for the amount of clusters and the current cluster the guilds shard is on but when I attempt to get all the clusters from the ShardManager I get ``Unsupported type 'function'.``. Is this possible to do?

**Comment by PandaDriver156** [comment]
You don't need to invoke the ShardingManager for that, the cluster count is saved as an environment variable. You can get it with `process.env.CLUSTER_CLUSTER_COUNT`.  The cluster id is also saved to the env variables, which you can get by doing `process.env.CLUSTER_ID`, but you also get it as `this.id` in your BaseCluster class.

**Comment by DevYukine** [comment]
Hey, depending on what information you want you can use the solution which @PandaDriver156 suggested, you have also access on these variables from the ShardClientUtil which is on the Client Class. Also could you do me the favor and show me what yexactly you tried to get all the cluster from the ShardManager?

**Comment by Puyodead1** [comment]
> 
> 
> You don't need to invoke the ShardingManager for that, the cluster count is saved as an environment variable. You can get it with `process.env.CLUSTER_CLUSTER_COUNT`. The cluster id is also saved to the env variables, which you can get by doing `process.env.CLUSTER_ID`, but you also get it as `this.id` in your BaseCluster class.

Ah cool, I'll give that a try.



> 
> 
> Hey, depending on what information you want you can use the solution which @PandaDriver156 suggested, you have also access on these variables from the ShardClientUtil which is on the Client Class. Also could you do me the favor and show me what yexactly you tried to get all the cluster from the ShardManager?

I was trying to access ShardManager#clusters, The ShardClientUtil wasn't showing like a of the clusters.
``this.client.shard.masterEval("this.clusters");`` is what I was trying to use

**Comment by DevYukine** [comment]
This seems done to me, if you have any issues with the solutions provided feel free to open again 😄
