### ISSUE TITLE
Error: Cluster 0 failed to start.

### ISSUE THREAD

**Issue by zero734kr** [DevYukine/Kurasuta#376]
![image](https://user-images.githubusercontent.com/51540538/88293279-2fc6a480-ccd1-11ea-8570-f90d06905258.jpeg)

Is there any reason for this failure? What is it caused by?

I can't start my bot due to this error and I tried to correct the verification of the open ipc port (ufw), token regeneration, reversion of my code (git reset) and is there any reason for that? Because I need to recover the state of the bot as soon as possible, but I already tried everything I remembered.

**Comment by DevYukine** [comment]
Seems like d.js never emits ready on your bot, are you on latest version of Kurasuta?

**Comment by zero734kr** [comment]
I upgraded to the latest version, but this error is still here. I will open the issue in discord.js, because I tested it with other code with same token and it didn't work also. Thanks for help.
