### ISSUE TITLE
[Need support] broadcastEval("this.guilds.cache") not working

### ISSUE THREAD

**Issue by SharifPoetra** [DevYukine/Kurasuta#383]
Hello there! I love to use kurasuta for sharding and keep your good work!
Here I just noticed that `broadcastEval("this.guilds.cache")` is always given an error says
```js
Error: Unsupported type 'function'.
```
But when I ask for someone who uses ShardingManager from discord.js directly, it's working fine:
![image](https://user-images.githubusercontent.com/43358217/94931607-7b5ab300-04b7-11eb-8c14-83daf373132b.png)

**Comment by RaknaXTR** [comment]
Try `this.guilds.cache.map(x => x.toJSON())`

**Comment by SharifPoetra** [comment]
Awesome, it works! thank you very much.
