### ISSUE TITLE
TypeError: ClusterClass is not a constructor

### ISSUE THREAD

**Issue by kakarot-dev** [DevYukine/Kurasuta#407]
This is the error im getting which trying to start the bot

then after that for no reason this error is showing up  Error: Cluster 0 failed to start

this is what i have rn
```
const {
    ShardingManager
} = require('kurasuta');
const {
    join
} = require('path');
require('dotenv').config()
const sharder = new ShardingManager(join(__dirname, 'bot.js'), {
    token: process.env.TOKEN,
    clusterCount: 3,
    guildsPerShard: 1
});

sharder.spawn();
```

**Comment by kakarot-dev** [comment]
i was trying this on a test bot which is only in two servers,
is that the prob?

**Comment by DevYukine** [comment]
your export is wrong, you need to export a class extending Cluster see the Readme for an example
